docs: update readme
paysuper/paysuper-analytics-lib-php pull request #1
Opened 2020-05-10 12:20 UTC by snezhana-dorogova

2020-05-14 16:08 UTC, EvgeniyStrigo requested changes

2020-05-14 16:08 UTC, EvgeniyStrigo commented on README.md
> +PaySuper Analytics is an SDK to implement to your backend server to collect data for financial and marketing reports.
sdk не поправлен

2020-05-14 16:08 UTC, EvgeniyStrigo commented on README.md
> +| |The PaySuper Analytics Architecture|
Блок с архитектурой надо взять из коллектора

2020-06-29 16:41 UTC, snezhana-dorogova commented
outdated

2020-06-29 16:41 UTC, closed without merging